# https://github.com/marketplace/actions/auto-assign-action
---

# # # # # # # # # # # # # # # #  # # # # # # # # # # # # # # #
# Reviewers
addReviewers: true
reviewers:
    - briandfoy
numberOfReviewers: 1

# # # # # # # # # # # # # # # #  # # # # # # # # # # # # # # #
# Assignees
addAssignees: true
assignees:
    - briandfoy
numberOfAssignees: 1
