# https://github.com/marketplace/actions/auto-assign-action
---

# # # # # # # # # # # # # # # #  # # # # # # # # # # # # # # #
# Reviewers
reviewers:
    - briandfoy
numberOfReviewers: 1

# # # # # # # # # # # # # # # #  # # # # # # # # # # # # # # #
# Assignees
assignees:
    - briandfoy
numberOfAssignees: 1
