name: "Manage opened pull request"
on:
    pull_request_target:
        types:
            - opened
jobs:
  manage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    environment: Release
    steps:
        - uses: actions/checkout@v3
        # https://github.com/marketplace/actions/labeler
        - uses: actions/labeler@v4
        # https://github.com/marketplace/actions/auto-assign-action
        - uses: kentaro-m/auto-assign-action@v1.2.5
