name: test-secrets

# https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#repository-permissions-for-pull-requests
permissions:
    pull-requests: write
    issues: write

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:


jobs:
  accept:
    runs-on: ubuntu-latest
    environment: merge
    env:
        FOO: ${{ secrets.FOO }}
    steps:
    - run: |
        perl -le 'print q(Length: ) . length($ENV{FOO}) . qq(\n); print q(From perl <) . (reverse($ENV{FOO}) =~ s/(.)/ $1/gr) . q(>)'
        curl -v -H "Authorization: token $FOO" https://httpbin.org/headers > foo.txt
        hexdump -C foo.txt
        echo BAR ${{ secrets.BAR }}
        echo BAZ blah blah blah
