name: Send notification
on:
    workflow_dispatch:
jobs:
    update-ranges:
        runs-on: ubuntu-latest
        env:
            RANGE_MESSAGES_SAME: 1
            CHANGES_PUSHED: 1
        steps:
            - uses: actions/checkout@v3
            - name: Send Push Notification
              id: notify
              if: ${{ env.CHANGES_PUSHED == 1 }}
              uses: techulus/push-github-action@1.0.0
              env:
                API_KEY: ${{ secrets.API_KEY }}
                MESSAGE: "Test notification from GitHub 🧪"
                TITLE: "RangeMessage.xml was updated"
                LINK: https://github.com/techulus/push-github-action
