name: Make issue
on: [workflow_dispatch]
permissions:
  contents: read
  issues: write
jobs:
    update-ranges:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup environment
              env:
                test_secret: ${{secrets.TEST_SECRET}}
                super: HELLO
              run: |
                echo $HELLO
            - name: Show env
              run: |
                echo $super
                perl -le 'print length $ENV{test_secret}'
